#!/usr/bin/env sh

# Global Variables
REPO_URL="https://raw.githubusercontent.com/howellcc/synology-prometheus/ForMe"
VERSION=$(curl -fsSL ${REPO_URL}/version | cat)
DOCKER_VOLUME="/home/chowell/docker"
PROMETHEUS_ROOT="${DOCKER_VOLUME}/prometheus"
GRAFANA_ROOT="${DOCKER_VOLUME}/grafana"
ALERTMANAGER_ROOT="${DOCKER_VOLUME}/alertmanager"
HOSTNAME=$(hostname -s)

# Throw Banner
echo "############################################################"
echo "# Synology Install Prometheus Stack Tool v${VERSION}"
echo "############################################################"

# Setup Prometheus File Structure
echo; echo ">>>>>> Setting up system File Structure"

prometheus_folders=( "configs" "data" )
for i in "${prometheus_folders[@]}"; do
  [ ! -d ${PROMETHEUS_ROOT}/${i} ] && mkdir -p ${PROMETHEUS_ROOT}/${i} \
  && echo "folder created ${PROMETHEUS_ROOT}/${i}"
done

# Setup Grafana File Structure
grafana_folders=( "configs" "data" )
for i in "${grafana_folders[@]}"; do
  [ ! -d ${GRAFANA_ROOT}/${i} ] && mkdir -p ${GRAFANA_ROOT}/${i} \
  && echo "folder created ${GRAFANA_ROOT}/${i}"
done

# Setup Alertmanager File Structure
alertmanager_folders=( "configs" "data" )
for i in "${alertmanager_folders[@]}"; do
  [ ! -d ${ALERTMANAGER_ROOT}/${i} ] && mkdir -p ${ALERTMANAGER_ROOT}/${i} \
  && echo "folder created ${ALERTMANAGER_ROOT}/${i}"
done

# Set permissions on the data file structures
# chown -R 99:99 ${PROMETHEUS_ROOT}/data #nobody userid
# chown -R 99:99 ${ALERTMANAGER_ROOT}/data #nobody userid
# chown -R 472:472 ${GRAFANA_ROOT}/data #grafana userid

# Download the default configs
curl -fsSL ${REPO_URL}/configs/prometheus.yml -o ${PROMETHEUS_ROOT}/configs/prometheus.yml
sed -i "s/\${HOSTNAME}/${HOSTNAME//\//\\/}/g" ${PROMETHEUS_ROOT}/configs/prometheus.yml
curl -fsSL ${REPO_URL}/configs/prometheus.rules -o ${PROMETHEUS_ROOT}/configs/prometheus.rules
curl -fsSL ${REPO_URL}/configs/alertmanager.yml -o ${ALERTMANAGER_ROOT}/configs/alertmanager.yml
curl -fsSL ${REPO_URL}/configs/grafana.ini -o ${GRAFANA_ROOT}/configs/grafana.ini

#chown -R 1032:100 ${PROMETHEUS_ROOT} #dockeruser userid
#chown -R 1032:100 ${ALERTMANAGER_ROOT} #dockeruser userid
#chown -R 1032:100 ${GRAFANA_ROOT} #dockeruser userid


echo; echo ">>>>>> Creating docker-compose file"
# Run docker-compose to stand up containers
curl -fsSL ${REPO_URL}/docker-compose.yml \
| sed "s/\${PROMETHEUS_ROOT}/${PROMETHEUS_ROOT//\//\\/}/g" \
| sed "s/\${ALERTMANAGER_ROOT}/${ALERTMANAGER_ROOT//\//\\/}/g" \
| sed "s/\${HOSTNAME}/${HOSTNAME//\//\\/}/g" \
| sed "s/\${GRAFANA_ROOT}/${GRAFANA_ROOT//\//\\/}/g" > ${PROMETHEUS_ROOT}/docker-compose.yml
echo "docker-compose file created ${PROMETHEUS_ROOT}/docker-compose.yml"

echo; echo ">>>>>> Running docker-compose file"
docker-compose -f ${PROMETHEUS_ROOT}/docker-compose.yml up -d
if [[ $? -eq 0 ]]; then
  echo; echo ">>>>>> Install successful, docker-compose successful"
elif [[ $? -ne 0 ]]; then
  echo; echo ">>>>>> Error during docker-compose, docker-compose exited with $?"
  exit 1
fi

# Finish
echo ">>>>>> Program Information"
echo "
#############################################
Grafana                  http://`hostname`:3000
Prometheus               http://`hostname`:9090
Alertmanager             http://`hostname`:9093
Node-Exporter            http://`hostname`:9100/metrics
Prometheus_reloader      nil
#############################################
"
